### ISSUE TITLE
The first item in the dropdown is not selected automatically

### ISSUE THREAD

**Issue by glebm** [yuku-t/textcomplete#93]
I've finally switched Thredded from jquery.textcomplete to textcomplete! https://github.com/thredded/thredded/pull/596

A couple of issues I've noticed:

1. There is no alternative to the previously emitted `change` event. I've worked around it like this:

   ```js
   textcomplete.on('select', () => {
     setTimeout(() => {
       textarea.dispatchEvent(new Event('input'));
     });
   });
   ```

   Opened #95

2. The first item in the dropdown is no longer focused automatically.

   Fixed in #94.

**Comment by yuku-t** [comment]
> I've finally switched Thredded from jquery.textcomplete to textcomplete! thredded/thredded#596

Great 👍 

> 2. The first item in the dropdown is no longer focused automatically.

When I was developing jquery-textcomplete, some developers asked me how to stop the behavior. (Sorry, I cannot show you the related comments, because the repository no longer accepts issues)

In this case, asking developers who need this to use following code is much easier and simpler than providing `dontSelectFirstItem` parameter, so I decided to drop the behavior from textcomplete.

```js
textcomplete.on('rendered', function () {
  if (textcomplete.dropdown.items.length) {
    // Activate the first item by default.
    textcomplete.dropdown.items[0].activate();
  }
});
```

**Comment by glebm** [comment]
Ah, OK, thank you
